config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      :sessions      => "users/sessions",
      :registrations => "users/registrations",
      :passwords     => "users/passwords"
    }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#index'
  resources :plans
  resources :todos
  resources :time_slot_todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/time_slot.rb
class TimeSlot < ApplicationRecord
  belongs_to :weekly_plan
  has_many :time_slot_todos
  has_many :todos, through: :time_slot_todos
  validates :start_time, uniqueness: { scope: [:weekly_plan_id] }
end

app/models/time_slot_todo.rb
class TimeSlotTodo < ApplicationRecord
  belongs_to :todo
  belongs_to :time_slot
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :time_slot_todos
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20],
        name: auth.info.name,
        cover: auth.info.image
      )
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/models/weekly_plan.rb
class WeeklyPlan < ApplicationRecord
  has_many :time_slots
  has_many :todos
  accepts_nested_attributes_for :time_slots
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :weekly_plan_status

  def weekly_plan_status
    if user_signed_in?
      @is_next_week_plan = WeeklyPlan.exists?(user_id: current_user.id, start_date: Date.today.beginning_of_week + 1.week)
      @is_this_week_plan = WeeklyPlan.exists?(user_id: current_user.id, start_date: Date.today.beginning_of_week)
    end
  end
end

app/controllers/concerns/common.rb
module Common
  extend ActiveSupport::Concern

  dayname = Date::ABBR_DAYNAMES.dup
  dayname.append(dayname.shift)
  DAYNAME = dayname

  def date_of_monday(week)
    if week == 'next'
      Date.today.beginning_of_week + 1.week
    else week == 'this'
      Date.today.beginning_of_week
    end
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  include Common

  def new(week='next')
    @monday = date_of_monday(week)

    start_time = @monday.to_time
    @slots = create_slots(start_time, DAYNAME)
    @week = week
  end

  def create(monday, status, week)
    @monday = monday
    @plan = WeeklyPlan.where(start_date: @monday, user_id: current_user.id).first_or_create
    status.each do |time|
      @plan.time_slots.build(
        start_time: time
      )
    end
    if @plan.save
      redirect_to new_todo_path(week: week)
    else
      @slots = create_slots(@monday.to_time, DAYNAME)
      render 'new'
    end
  end

  def index(week='next')
    @week = week
    next_monday = date_of_monday(@week)

    start_time = next_monday.to_time
    @slots = create_slots(start_time, DAYNAME)

    @plan = WeeklyPlan.find_by(start_date: next_monday, user_id: current_user.id)
    if @plan.blank?
      redirect_to new_plan_path(week: week)
    end

    @start_times = []
    @slot_todos = {}
    @todo_ids = []
    time_slots = TimeSlot.where(weekly_plan: @plan.id).includes(:todos)
    time_slots.each do |time_slot|
      if !time_slot.todos[0].nil?
        @start_times.append(time_slot.start_time)
        @slot_todos[time_slot.start_time] = time_slot.todos[0]
        @todo_ids << time_slot.todos[0].id
      end
    end
    @todo_ids = @todo_ids.uniq
    @todos = Todo.where(id: @todo_ids)
    @todo_colors = ['#D04E5A', '#E2714D', '#F3C24E', '#8BB14F', '#61BFB0', '#5DB4DD', '#7E8AE4', '#B087E7', '#D37CB4', '#D74E46']
  end

  def show(id)
  end

  private

  def create_slots(start_time, dayname)
    slots = []

    dayname.each do |day|
      daily_slots = []
      48.times do
        daily_slots.append(start_time)
        start_time += 30.minutes
      end
      slots.append([day, daily_slots])
    end
    return slots
  end
end

app/controllers/time_slot_todos_controller.rb
class TimeSlotTodosController < ApplicationController
  include Common

  def new(week='next')
    @monday = date_of_monday(week)

    plan = WeeklyPlan.find_by(user_id: current_user.id, start_date: @monday)

    todos = plan.todos
    time_slots = plan.time_slots

    assignment = []
    todos.each do |todo|
      slot_num = (todo.hours/0.5).to_i
      slot_num.times do
        assignment.append(todo.id)
      end
    end

    assignment.shuffle!
    assignment.each.with_index do |task_id, i|
      TimeSlotTodo.where(
        time_slot_id: time_slots[i]
      ).first_or_create(
        todo_id: task_id,
        weekly_plan_id: plan.id
      )
    end
    redirect_to root_path
  end

  def show(id)
    @time_slot_todo = TimeSlotTodo.find(id)
  end

  def update(id)
    @time_slot_todo = TimeSlotTodo.find(id)
    @time_slot_todo.update(status: true)
    redirect_to root_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  include Common

  def new(week='next')
    @monday = date_of_monday(week)

    @plan = WeeklyPlan.find_by(user_id: current_user.id, start_date: @monday)
    slots = @plan.time_slots
    @slots_count = slots.count
    @select_options = []
    @slots_count.times.with_index do |i|
      @select_options.append((i+1)*0.5)
    end
    @week = week
  end

  def create(todo, plan_id, max_time, week='next')
    hours = 0
    decided_todos = Todo.where(weekly_plan_id: plan_id)
    decided_time = decided_todos.inject(0){|sum, decided_todo| sum + decided_todo.hours}

    todo.each.with_index(1) do |parameter, i|
      if parameter[:name].present? && parameter[:hours].present?
        hours += parameter[:hours].to_f
        if hours > max_time.to_f - decided_time
          break
        end
        Todo.create(
          name: parameter[:name],
          hours: parameter[:hours].to_f,
          weekly_plan_id: plan_id,
          priority: i
        )
      end
    end
    redirect_to new_time_slot_todo_path(week: week)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  include Common

  def index
    if user_signed_in?
      @user = User.find(current_user.id)
      monday = date_of_monday('this')
      plan = WeeklyPlan.find_by(start_date: monday, user_id: current_user.id)
      if plan.nil?
        redirect_to new_plan_path and return
      end
      @time_slots = TimeSlot.where(weekly_plan_id: plan.id).where(start_time: [Date.today..Date.tomorrow]).includes(todos: :time_slot_todos)
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController
  def facebook
    callback_from :facebook
  end

=begin
  def twitter
    callback_from :twitter
  end
=end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      session["#{provider}_data"] = request.env['omniauth.auth']
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < ApplicationController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def destroy
    super
    session['facebook_data'] = {}
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def destroy
    super
    session['facebook_data'] = {}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def week_name(week)
    if week == 'this'
      "今週"
    else week == 'next'
      "来週"
    end
  end
end

app/views/layouts/_nav.html.haml
%nav#my-menu
  %ul.wrap_ul
    - if user_signed_in?
      %li
        %p.header_prof
          %img{ src: current_user.cover, width: '40px', height: '40px' }
          %span= current_user.name
      %li
        = link_to root_path do
          %i.fa.fa-home
          %span HOME
      - if @is_this_week_plan
        %li
          = link_to plans_path(week: 'this') do
            %i.fa.fa-calendar
            %span 今週のプラン
      - else
        %li
          = link_to new_plan_path(week: 'this') do
            %i.fa.fa-calendar-plus-o
            %span 今週のプランを立てる
      - if @is_next_week_plan
        %li
          = link_to plans_path do
            %i.fa.fa-calendar
            %span 来週のプラン
      - else
        %li
          = link_to new_plan_path do
            %i.fa.fa-calendar-plus-o
            %span 来週のプランを立てる
      %li
        = link_to destroy_user_session_path, method: :delete do
          %i.fa.fa-sign-out
          %span ログアウト
    - else
      %li
        = link_to user_facebook_omniauth_authorize_path do
          %i.fa.fa-facebook-square
          %span 無料Facebookログイン

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" }
    %title PomodoroLife
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    - if (head = yield(:head)).present?
      = head
  %body
    = render 'layouts/nav'
    .wrapper
      #nomal_view
        %header#header.container
          .content.dropdown
            %h1
              = link_to root_path do
                = image_tag 'logo.png', width: '113px', height: '27px', alt: "pomodoro-life"
            = link_to "#my-menu", id: "my-menu-button", class: 'menu_button' do
              %i.fa.fa-bars
        #page_wrap
          = yield

app/views/plans/index.html.haml
- content_for :head do
  = stylesheet_link_tag 'plan'

%div{ style: 'margin: 0 auto;'}
  .colorkeys
    %p.plantitle= "#{week_name(@week)}のプラン"
    .container
      .row{ style: 'padding: 0;'}
        - @todo_ids.each do |id|
          .col-xs-6{ style: 'font-size: 11px'}
            .colorcircle{ style: "float: left; width: 15px; height: 15px; border-radius: 20px; margin-top: 2px; background-color: #{@todo_colors[id]};"}
            %p.todoname= @todos[id-1]['name']

  .clearfix
    .container
      .row.table
        .col-xs-1.slotlist
          .clearfix
            - @slots[0][1].each do |slot|
              %p.times= slot.strftime("%H:%M~")

        .col-xs-10.slottable
          .clearfix.days{ style: 'position: fixed; width: 80%; top: 44px;'}
            - @slots.each do |day|
              %p.days= day[0]
          .clearfix
            = form_tag '/plans', method: 'post' do
              = hidden_field_tag :monday, @monday
              = hidden_field_tag :week, @week
              - @slots.each do |day|
                %div{ style: 'width: 14%; float: left;' }
                  - day[1].each do |slot|
                    - if @start_times.include?(slot)
                      %p.slot{ style: "color: white; background-color: #{@todo_colors[@slot_todos[slot]['id']]};"}
                    - else
                      %p.slot.originalBackground

app/views/plans/new.html.haml
- content_for :head do
  = stylesheet_link_tag 'plan'

%div{ style: 'margin: 0 auto;'}
  .newtodotitle
    = "#{@monday.strftime("%m/%d")} (Mon) ~ #{(@monday + 6.days).strftime("%m/%d")} (Sun)"
    = "でTODO項目に使える時間を選ぶ"

  .container
    .row
      .col-xs-1.slotlist
        .clearfix
          - @slots[0][1].each do |slot|
            %p.times= slot.strftime("%H:%M~")

      .col-xs-10.slottable
        .clearfix{ style: 'position: fixed; width: 80%; top: 45px;'}
          - @slots.each do |day|
            %p.days= day[0]
        .clearfix
          = form_tag '/plans', method: 'post' do
            = hidden_field_tag :monday, @monday
            = hidden_field_tag :week, @week
            - @slots.each do |day|
              %div{ style: 'width: 14%; float: left;' }
                - day[1].each do |slot|
                  - if slot >= Time.now() - 30.minutes
                    %p.slot.originalBackground
                      = label_tag "status[]", ""
                      = check_box_tag "status[]", slot
                  - else
                    %p.slot.disabled_slot_box
                      = label_tag "status[]", ""
                      = check_box_tag "status[]", slot, false, { disabled: true }
              = submit_tag '▷', class: 'btn btn-primary'

:javascript
  $(function(){
    $("input[type='checkbox']").on('change', function(){
    if($(this).is(":checked")){
        $(this).parent().removeClass("originalBackground");
        $(this).parent().addClass("selectedBackground");
        console.log($(this).parent());
    }
    else{
        $(this).parent().removeClass("selectedBackground");
    } });
  });

app/views/time_slot_todos/show.html.haml
- content_for :head do
  = stylesheet_link_tag 'timer'
  = javascript_include_tag 'jquery.simple.timer.js'

.taskdisplay
  = @time_slot_todo.todo.name

.timerdisplay
  .timer.clearfix
    .hours 00:
    .minutes 00:
    .seconds 10
    .clearDiv
= image_tag("start.png", class: 'timer-button', id: "start")
= image_tag("restart.png", class: 'timer-button', id: "stop", style: "display:none;")

#responsive.modal.fade{ tabindex: "-1", data: { width: "760" }, style: 'display:none;' }
  .modal-dialog{ role: 'document' }
    .modal-content
      .modal-header
        %button.close{ type: "button", data: { dismiss: "modal" }, aria: { hidden: "true" } }
          = "x"
        %h3 Congratulation!
      .modal-body
        = link_to "完了！次へ！", time_slot_todo_path(@time_slot_todo.id), method: :PATCH

:javascript
  $('#start').on('click', function(){
    $('.timerdisplay').empty()
    $('.timerdisplay').append('<div class="timer clearfix" data-seconds-left="10"></div>')
    $('.timer').startTimer({
      allowPause: true,
      onComplete: function() {
        $('.timerdisplay').empty()
        $('.timerdisplay').append('<div class="timer"><div class="hours">00:</div><div class="minutes">00:</div><div class="seconds">00</div><div class="clearDiv"></div></div>')
        $('#responsive').modal('show');
      }
    });
    $("#start").css('display', 'none');
    $("#stop").css('display', 'block');
  });
  $('#stop').on('click', function(){
    $('.timerdisplay').empty()
    $('.timerdisplay').append('<div class="timer"><div class="hours">00:</div><div class="minutes">00:</div><div class="seconds">10</div><div class="clearDiv"></div></div>')
    $("#start").css('display', 'block');
    $("#stop").css('display', 'none');
  });

app/views/todos/new.html.haml
- content_for :head do
  = stylesheet_link_tag 'todo'

%div{ style: 'margin: 0 auto; padding: 0 10px 0 10px;'}
  .newtodotitle
    = "#{@monday.strftime("%m/%d")} (Mon) ~ #{(@monday + 6.days).strftime("%m/%d")} (Sun)"
    = "　　合計: #{@slots_count*0.5}時間"

    %br

    ="TODO項目を決める"
    %br

  = form_tag '/todos' do

    .todo
      = hidden_field_tag 'plan_id', @plan.id
      = hidden_field_tag 'max_time', @slots_count*0.5
      = hidden_field_tag 'week', @week
      .container
        - 10.times do |i|
          .row.todopanel
            .col-xs-1
              %p= "#{i+1}"
            .col-xs-8
              = text_field_tag "todo[][name]"
            .col-xs-3
              = select_tag 'todo[][hours]', options_for_select(@select_options)
      = submit_tag '▷', class: 'btn btn-primary'

app/views/top/index.html.haml
- content_for :head do
  = stylesheet_link_tag 'timer'
  = javascript_include_tag 'jquery.simple.timer.js'

- if user_signed_in?
  .container
    %p{ style: "font-size: 18px; color:#D55C4B" } 今日のスケジュール


  .table-responsive
    %table.table{ data: { toggle: "table", height: "299" }, style: 'max-width: 800px;margin: 0 auto' }
      %thead
        %tr{ style: "font-size:12px;color:#666" }
          %th{ style: "padding:11px" }
          %th{ style: "padding:5px; width: 115px; color:#D55C4B" } 時間
          %th{ style: "padding:5px; color:#D55C4B" } タイトル
        - @time_slots.each.with_index do |slot, i|
          - todo = slot.todos
          - slot_id = slot.time_slot_todos[0].id
          - class_name = 'not_yet'
          - is_clear = false
          - if slot.start_time < Time.now - 30.minutes
            - class_name = 'end_todo'
          - if slot.time_slot_todos[0].status
            - class_name = 'end_todo'
            - is_clear = true
          = link_to time_slot_todo_path(slot_id) do
            %tr{ class: "#{class_name}" }
              %td{ class: "#{(is_clear)?'selected':''}" }
              %td= "#{slot.start_time.strftime("%H:%M")} ~ #{(slot.start_time + 30.minutes).strftime("%H:%M")}"
              %td= link_to todo[0].name, time_slot_todo_path(slot_id)

- else
  .timerdisplay{ style: "margin-top: 50px;" }
    .timer.clearfix
      .hours 00:
      .minutes 25:
      .seconds 00
      .clearDiv
  = image_tag("start.png", class: 'timer-button', id: "start")
  = image_tag("restart.png", class: 'timer-button', id: "stop", style: "display:none;")

:javascript
  $('#start').on('click', function(){
    $('.timerdisplay').empty()
    $('.timerdisplay').append('<div class="timer clearfix" data-minutes-left="25"></div>')
    $('.timer').startTimer({
      allowPause: true
    });
    $("#start").css('display', 'none');
    $("#stop").css('display', 'block');
  });
  $('#stop').on('click', function(){
    $('.timerdisplay').empty()
    $('.timerdisplay').append('<div class="timer"><div class="hours">00:</div><div class="minutes">25:</div><div class="seconds">00</div><div class="clearDiv"></div></div>')
    $("#start").css('display', 'block');
    $("#stop").css('display', 'none');
  });
  $("td").click(function(){
    var url = $(this).parent("tr").find("td a:first-child").attr("href");
    window.location = url;
  });